# Makefile.in generated automatically by automake 1.4-p5 from Makefile.am

# Copyright (C) 1994, 1995-8, 1999, 2001 Free Software Foundation, Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.


SHELL = /bin/sh

srcdir = .
top_srcdir = ../..

prefix = /opt/local
exec_prefix = ${prefix}

bindir = ${exec_prefix}/bin
sbindir = ${exec_prefix}/sbin
libexecdir = ${exec_prefix}/libexec
datadir = ${prefix}/share
sysconfdir = ${prefix}/etc
sharedstatedir = ${prefix}/com
localstatedir = ${prefix}/var
libdir = ${exec_prefix}/lib
infodir = ${prefix}/share/info
mandir = ${prefix}/share/man
includedir = ${prefix}/include
oldincludedir = /usr/include

DESTDIR =

pkgdatadir = $(datadir)/glade
pkglibdir = $(libdir)/glade
pkgincludedir = $(includedir)/glade

top_builddir = ../..

ACLOCAL = ${SHELL} /private/var/root/Downloads/glade-1.1.3/missing --run aclocal-1.11
AUTOCONF = ${SHELL} /private/var/root/Downloads/glade-1.1.3/missing --run autoconf
AUTOMAKE = ${SHELL} /private/var/root/Downloads/glade-1.1.3/missing --run automake-1.11
AUTOHEADER = ${SHELL} /private/var/root/Downloads/glade-1.1.3/missing --run autoheader

INSTALL = /usr/bin/install -c
INSTALL_PROGRAM = ${INSTALL} $(AM_INSTALL_PROGRAM_FLAGS)
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_SCRIPT = ${INSTALL}
transform = s,x,x,

NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
host_alias = 
host_triplet = x86_64-apple-darwin11.4.2
AS = @AS@
CATALOGS = 
CATOBJEXT = NONE
CC = gcc
DATADIRNAME = lib
DLLTOOL = false
ECHO = @ECHO@
EXEEXT = 
GETTEXT_PACKAGE = glade-2.0
GLADE_CFLAGS = -I/sw/include/libxml2 -I/sw/include -I/sw/include/gtk-2.0 -I/sw/lib/gtk-2.0/include -I/sw/include/atk-1.0 -I/sw/include/cairo -I/sw/include/pango-1.0 -I/sw/include/glib-2.0 -I/sw/lib/glib-2.0/include -I/sw/include/freetype2 -I/sw/include/libgnomeui-2.0 -I/sw/include/libgnome-2.0 -I/sw/include/libbonoboui-2.0 -I/sw/include/libgnomecanvas-2.0 -I/sw/include/gnome-vfs-2.0 -I/sw/lib/gnome-vfs2.16/gnome-vfs-2.0/include -I/sw/include/libbonobo-2.0 -I/sw/include/orbit-2.0 -I/sw/include/bonobo-activation-2.0 -I/sw/include/libart-2.0 -I/sw/include/gconf/2 -I/usr/X11/include -DORBIT2=1 
GLADE_DEPRECATION_CFLAGS = 
GLADE_GNOME_DB_DIR = 
GLADE_GNOME_DB_LIB = 
GLADE_GNOME_DIR = gnome
GLADE_GNOME_LIB = gnome/libgnomewidgets.a
GLADE_LIBS = -L/sw/lib -L/sw/lib/gnome-vfs2.16 -L/usr/X11/lib -lxml2 -lgnomeui-2 -lSM -lICE -lgnomevfs-2 -lgconf-2 -lbonoboui-2 -lgnomecanvas-2 -lgnome-2 -lpopt -lart_lgpl_2 -lgtk-x11-2.0 -lgdk-x11-2.0 -latk-1.0 -lgio-2.0 -lpangoft2-1.0 -lgdk_pixbuf-2.0 -lpangocairo-1.0 -lcairo -lpango-1.0 -lfreetype -lfontconfig -lbonobo-2 -lbonobo-activation -lgmodule-2.0 -lORBit-2 -lgthread-2.0 -lgobject-2.0 -lglib-2.0 -lintl  -L/usr/X11/lib -R/usr/X11/lib  -lSM -lICE -lX11 
GMOFILES =  az.gmo ca.gmo cs.gmo da.gmo de.gmo el.gmo en_GB.gmo es.gmo fr.gmo ga.gmo gl.gmo hu.gmo it.gmo ja.gmo ko.gmo lv.gmo nn.gmo no.gmo pl.gmo pt.gmo pt_BR.gmo ro.gmo ru.gmo sk.gmo sv.gmo tr.gmo uk.gmo vi.gmo zh_CN.gmo
GMSGFMT = /sw/bin/msgfmt
INSTOBJEXT = 
INTLDEPS = @INTLDEPS@
INTLLIBS = 
INTLOBJS = @INTLOBJS@
INTLTOOL_CAVES_RULE = %.caves:     %.caves.in     $(INTLTOOL_MERGE) $(wildcard $(top_srcdir)/po/*.po) ; $(INTLTOOL_V_MERGE)LC_ALL=C $(INTLTOOL_MERGE) $(INTLTOOL_V_MERGE_OPTIONS) -d -u -c $(top_builddir)/po/.intltool-merge-cache $(top_srcdir)/po $< $@
INTLTOOL_DESKTOP_RULE = %.desktop:   %.desktop.in   $(INTLTOOL_MERGE) $(wildcard $(top_srcdir)/po/*.po) ; $(INTLTOOL_V_MERGE)LC_ALL=C $(INTLTOOL_MERGE) $(INTLTOOL_V_MERGE_OPTIONS) -d -u -c $(top_builddir)/po/.intltool-merge-cache $(top_srcdir)/po $< $@
INTLTOOL_DIRECTORY_RULE = %.directory: %.directory.in $(INTLTOOL_MERGE) $(wildcard $(top_srcdir)/po/*.po) ; $(INTLTOOL_V_MERGE)LC_ALL=C $(INTLTOOL_MERGE) $(INTLTOOL_V_MERGE_OPTIONS) -d -u -c $(top_builddir)/po/.intltool-merge-cache $(top_srcdir)/po $< $@
INTLTOOL_EXTRACT = /sw/bin/intltool-extract
INTLTOOL_KEYS_RULE = %.keys:      %.keys.in      $(INTLTOOL_MERGE) $(wildcard $(top_srcdir)/po/*.po) ; $(INTLTOOL_V_MERGE)LC_ALL=C $(INTLTOOL_MERGE) $(INTLTOOL_V_MERGE_OPTIONS) -k -u -c $(top_builddir)/po/.intltool-merge-cache $(top_srcdir)/po $< $@
INTLTOOL_MERGE = /sw/bin/intltool-merge
INTLTOOL_OAF_RULE = %.oaf:       %.oaf.in       $(INTLTOOL_MERGE) $(wildcard $(top_srcdir)/po/*.po) ; $(INTLTOOL_V_MERGE)LC_ALL=C $(INTLTOOL_MERGE) $(INTLTOOL_V_MERGE_OPTIONS) -o -p $(top_srcdir)/po $< $@
INTLTOOL_PERL = /usr/bin/perl
INTLTOOL_PONG_RULE = %.pong:      %.pong.in      $(INTLTOOL_MERGE) $(wildcard $(top_srcdir)/po/*.po) ; $(INTLTOOL_V_MERGE)LC_ALL=C $(INTLTOOL_MERGE) $(INTLTOOL_V_MERGE_OPTIONS) -x -u -c $(top_builddir)/po/.intltool-merge-cache $(top_srcdir)/po $< $@
INTLTOOL_PROP_RULE = %.prop:      %.prop.in      $(INTLTOOL_MERGE) $(wildcard $(top_srcdir)/po/*.po) ; $(INTLTOOL_V_MERGE)LC_ALL=C $(INTLTOOL_MERGE) $(INTLTOOL_V_MERGE_OPTIONS) -d -u -c $(top_builddir)/po/.intltool-merge-cache $(top_srcdir)/po $< $@
INTLTOOL_SCHEMAS_RULE = %.schemas:   %.schemas.in   $(INTLTOOL_MERGE) $(wildcard $(top_srcdir)/po/*.po) ; $(INTLTOOL_V_MERGE)LC_ALL=C $(INTLTOOL_MERGE) $(INTLTOOL_V_MERGE_OPTIONS) -s -u -c $(top_builddir)/po/.intltool-merge-cache $(top_srcdir)/po $< $@
INTLTOOL_SERVER_RULE = %.server:    %.server.in    $(INTLTOOL_MERGE) $(wildcard $(top_srcdir)/po/*.po) ; $(INTLTOOL_V_MERGE)LC_ALL=C $(INTLTOOL_MERGE) $(INTLTOOL_V_MERGE_OPTIONS) -o -u -c $(top_builddir)/po/.intltool-merge-cache $(top_srcdir)/po $< $@
INTLTOOL_SHEET_RULE = %.sheet:     %.sheet.in     $(INTLTOOL_MERGE) $(wildcard $(top_srcdir)/po/*.po) ; $(INTLTOOL_V_MERGE)LC_ALL=C $(INTLTOOL_MERGE) $(INTLTOOL_V_MERGE_OPTIONS) -x -u -c $(top_builddir)/po/.intltool-merge-cache $(top_srcdir)/po $< $@
INTLTOOL_SOUNDLIST_RULE = %.soundlist: %.soundlist.in $(INTLTOOL_MERGE) $(wildcard $(top_srcdir)/po/*.po) ; $(INTLTOOL_V_MERGE)LC_ALL=C $(INTLTOOL_MERGE) $(INTLTOOL_V_MERGE_OPTIONS) -d -u -c $(top_builddir)/po/.intltool-merge-cache $(top_srcdir)/po $< $@
INTLTOOL_UI_RULE = %.ui:        %.ui.in        $(INTLTOOL_MERGE) $(wildcard $(top_srcdir)/po/*.po) ; $(INTLTOOL_V_MERGE)LC_ALL=C $(INTLTOOL_MERGE) $(INTLTOOL_V_MERGE_OPTIONS) -x -u -c $(top_builddir)/po/.intltool-merge-cache $(top_srcdir)/po $< $@
INTLTOOL_UPDATE = /sw/bin/intltool-update
INTLTOOL_XML_RULE = %.xml:       %.xml.in       $(INTLTOOL_MERGE) $(wildcard $(top_srcdir)/po/*.po) ; $(INTLTOOL_V_MERGE)LC_ALL=C $(INTLTOOL_MERGE) $(INTLTOOL_V_MERGE_OPTIONS) -x -u -c $(top_builddir)/po/.intltool-merge-cache $(top_srcdir)/po $< $@
LIBTOOL = $(SHELL) $(top_builddir)/libtool
LN_S = ln -s
MAINT = #
MAKEINFO = ${SHELL} /private/var/root/Downloads/glade-1.1.3/missing --run makeinfo
MKINSTALLDIRS = ./mkinstalldirs
OBJDUMP = false
OBJEXT = o
PACKAGE = glade
PKG_CONFIG = /sw/bin/pkg-config
POFILES =  az.po ca.po cs.po da.po de.po el.po en_GB.po es.po fr.po ga.po gl.po hu.po it.po ja.po ko.po lv.po nn.po no.po pl.po pt.po pt_BR.po ro.po ru.po sk.po sv.po tr.po uk.po vi.po zh_CN.po
POSUB = po
RANLIB = ranlib
SCROLLKEEPER_CONFIG = /sw/bin/scrollkeeper-config
SCROLLKEEPER_REQUIRED = 0.1.4
STRIP = strip
USE_NLS = yes
VERSION = 1.1.3

noinst_LIBRARIES = libgnomedbwidgets.a

INCLUDES = $(GLADE_CFLAGS) 	$(GLADE_DEPRECATION_CFLAGS)


libgnomedbwidgets_a_SOURCES =  	gnomedbbrowser.c 	gnomedbcombo.c 	gnomedbconnectsel.c 	gnomedbdsnconfig.c 	gnomedbdsndruid.c 	gnomedberror.c 	gnomedberrordlg.c 	gnomedbform.c 	gnomedbgrid.c 	gnomedblist.c 	gnomedblogin.c 	gnomedblogindlg.c 	gnomedbprovidersel.c 	gnomedbsourcesel.c 	gnomedbsqleditor.c 	gnomedbtableeditor.c

mkinstalldirs = $(SHELL) $(top_srcdir)/mkinstalldirs
CONFIG_HEADER = ../../config.h
CONFIG_CLEAN_FILES = 
LIBRARIES =  $(noinst_LIBRARIES)


DEFS = -DHAVE_CONFIG_H -I. -I$(srcdir) -I../..
CPPFLAGS = -I/opt/local/include
LDFLAGS = 
LIBS = 
X_CFLAGS = 
X_LIBS =  -L/usr/X11/lib -R/usr/X11/lib
X_EXTRA_LIBS = 
X_PRE_LIBS =  -lSM -lICE
libgnomedbwidgets_a_LIBADD = 
libgnomedbwidgets_a_OBJECTS =  gnomedbbrowser.$(OBJEXT) \
gnomedbcombo.$(OBJEXT) gnomedbconnectsel.$(OBJEXT) \
gnomedbdsnconfig.$(OBJEXT) gnomedbdsndruid.$(OBJEXT) \
gnomedberror.$(OBJEXT) gnomedberrordlg.$(OBJEXT) gnomedbform.$(OBJEXT) \
gnomedbgrid.$(OBJEXT) gnomedblist.$(OBJEXT) gnomedblogin.$(OBJEXT) \
gnomedblogindlg.$(OBJEXT) gnomedbprovidersel.$(OBJEXT) \
gnomedbsourcesel.$(OBJEXT) gnomedbsqleditor.$(OBJEXT) \
gnomedbtableeditor.$(OBJEXT)
AR = ar
CFLAGS = -g -O2
COMPILE = $(CC) $(DEFS) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
LTCOMPILE = $(LIBTOOL) --mode=compile $(CC) $(DEFS) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
CCLD = $(CC)
LINK = $(LIBTOOL) --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) $(LDFLAGS) -o $@
DIST_COMMON =  Makefile.am Makefile.in


DISTFILES = $(DIST_COMMON) $(SOURCES) $(HEADERS) $(TEXINFOS) $(EXTRA_DIST)

TAR = gtar
GZIP_ENV = --best
SOURCES = $(libgnomedbwidgets_a_SOURCES)
OBJECTS = $(libgnomedbwidgets_a_OBJECTS)

all: all-redirect
.SUFFIXES:
.SUFFIXES: .S .c .lo .o .obj .s
$(srcdir)/Makefile.in: # Makefile.am $(top_srcdir)/configure.in $(ACLOCAL_M4) 
	cd $(top_srcdir) && $(AUTOMAKE) --gnu --include-deps glade/gnome-db/Makefile

Makefile: $(srcdir)/Makefile.in  $(top_builddir)/config.status
	cd $(top_builddir) \
	  && CONFIG_FILES=$(subdir)/$@ CONFIG_HEADERS= $(SHELL) ./config.status


mostlyclean-noinstLIBRARIES:

clean-noinstLIBRARIES:
	-test -z "$(noinst_LIBRARIES)" || rm -f $(noinst_LIBRARIES)

distclean-noinstLIBRARIES:

maintainer-clean-noinstLIBRARIES:

.c.o:
	$(COMPILE) -c $<

# FIXME: We should only use cygpath when building on Windows,
# and only if it is available.
.c.obj:
	$(COMPILE) -c `cygpath -w $<`

.s.o:
	$(COMPILE) -c $<

.S.o:
	$(COMPILE) -c $<

mostlyclean-compile:
	-rm -f *.o core *.core
	-rm -f *.$(OBJEXT)

clean-compile:

distclean-compile:
	-rm -f *.tab.c

maintainer-clean-compile:

.c.lo:
	$(LIBTOOL) --mode=compile $(COMPILE) -c $<

.s.lo:
	$(LIBTOOL) --mode=compile $(COMPILE) -c $<

.S.lo:
	$(LIBTOOL) --mode=compile $(COMPILE) -c $<

mostlyclean-libtool:
	-rm -f *.lo

clean-libtool:
	-rm -rf .libs _libs

distclean-libtool:

maintainer-clean-libtool:

libgnomedbwidgets.a: $(libgnomedbwidgets_a_OBJECTS) $(libgnomedbwidgets_a_DEPENDENCIES)
	-rm -f libgnomedbwidgets.a
	$(AR) cru libgnomedbwidgets.a $(libgnomedbwidgets_a_OBJECTS) $(libgnomedbwidgets_a_LIBADD)
	$(RANLIB) libgnomedbwidgets.a

tags: TAGS

ID: $(HEADERS) $(SOURCES) $(LISP)
	list='$(SOURCES) $(HEADERS)'; \
	unique=`for i in $$list; do echo $$i; done | \
	  awk '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	here=`pwd` && cd $(srcdir) \
	  && mkid -f$$here/ID $$unique $(LISP)

TAGS:  $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) $(LISP)
	tags=; \
	here=`pwd`; \
	list='$(SOURCES) $(HEADERS)'; \
	unique=`for i in $$list; do echo $$i; done | \
	  awk '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	test -z "$(ETAGS_ARGS)$$unique$(LISP)$$tags" \
	  || (cd $(srcdir) && etags $(ETAGS_ARGS) $$tags  $$unique $(LISP) -o $$here/TAGS)

mostlyclean-tags:

clean-tags:

distclean-tags:
	-rm -f TAGS ID

maintainer-clean-tags:

distdir = $(top_builddir)/$(PACKAGE)-$(VERSION)/$(subdir)

subdir = glade/gnome-db

distdir: $(DISTFILES)
	@for file in $(DISTFILES); do \
	  d=$(srcdir); \
	  if test -d $$d/$$file; then \
	    cp -pr $$d/$$file $(distdir)/$$file; \
	  else \
	    test -f $(distdir)/$$file \
	    || ln $$d/$$file $(distdir)/$$file 2> /dev/null \
	    || cp -p $$d/$$file $(distdir)/$$file || :; \
	  fi; \
	done
gnomedbbrowser.o: gnomedbbrowser.c ../../config.h ../gb.h \
	../gladeconfig.h ../debug.h ../editor.h ../gbwidget.h \
	../glade.h ../styles.h ../glade_widget_data.h ../glade-parser.h \
	../gbsource.h ../glade_project.h ../load.h ../property.h \
	../save.h ../source.h ../utils.h \
	../graphics/gnome-db-browser.xpm
gnomedbcombo.o: gnomedbcombo.c ../../config.h ../gb.h ../gladeconfig.h \
	../debug.h ../editor.h ../gbwidget.h ../glade.h ../styles.h \
	../glade_widget_data.h ../glade-parser.h ../gbsource.h \
	../glade_project.h ../load.h ../property.h ../save.h \
	../source.h ../utils.h ../graphics/gnome-db-combo.xpm
gnomedbconnectsel.o: gnomedbconnectsel.c ../../config.h ../gb.h \
	../gladeconfig.h ../debug.h ../editor.h ../gbwidget.h \
	../glade.h ../styles.h ../glade_widget_data.h ../glade-parser.h \
	../gbsource.h ../glade_project.h ../load.h ../property.h \
	../save.h ../source.h ../utils.h \
	../graphics/gnome-db-connectsel.xpm
gnomedbdsnconfig.o: gnomedbdsnconfig.c ../../config.h ../gb.h \
	../gladeconfig.h ../debug.h ../editor.h ../gbwidget.h \
	../glade.h ../styles.h ../glade_widget_data.h ../glade-parser.h \
	../gbsource.h ../glade_project.h ../load.h ../property.h \
	../save.h ../source.h ../utils.h \
	../graphics/gnome-db-dsnconfig.xpm
gnomedbdsndruid.o: gnomedbdsndruid.c ../../config.h ../gb.h \
	../gladeconfig.h ../debug.h ../editor.h ../gbwidget.h \
	../glade.h ../styles.h ../glade_widget_data.h ../glade-parser.h \
	../gbsource.h ../glade_project.h ../load.h ../property.h \
	../save.h ../source.h ../utils.h \
	../graphics/gnome-db-dsn-druid.xpm
gnomedberror.o: gnomedberror.c ../../config.h ../gb.h ../gladeconfig.h \
	../debug.h ../editor.h ../gbwidget.h ../glade.h ../styles.h \
	../glade_widget_data.h ../glade-parser.h ../gbsource.h \
	../glade_project.h ../load.h ../property.h ../save.h \
	../source.h ../utils.h ../graphics/gnome-db-error.xpm
gnomedberrordlg.o: gnomedberrordlg.c ../../config.h ../gb.h \
	../gladeconfig.h ../debug.h ../editor.h ../gbwidget.h \
	../glade.h ../styles.h ../glade_widget_data.h ../glade-parser.h \
	../gbsource.h ../glade_project.h ../load.h ../property.h \
	../save.h ../source.h ../utils.h \
	../graphics/gnome-db-error-dlg.xpm
gnomedbform.o: gnomedbform.c ../../config.h ../gb.h ../gladeconfig.h \
	../debug.h ../editor.h ../gbwidget.h ../glade.h ../styles.h \
	../glade_widget_data.h ../glade-parser.h ../gbsource.h \
	../glade_project.h ../load.h ../property.h ../save.h \
	../source.h ../utils.h ../graphics/gnome-db-form.xpm
gnomedbgrid.o: gnomedbgrid.c ../../config.h ../gb.h ../gladeconfig.h \
	../debug.h ../editor.h ../gbwidget.h ../glade.h ../styles.h \
	../glade_widget_data.h ../glade-parser.h ../gbsource.h \
	../glade_project.h ../load.h ../property.h ../save.h \
	../source.h ../utils.h ../graphics/gnome-db-grid.xpm
gnomedblist.o: gnomedblist.c ../../config.h ../gb.h ../gladeconfig.h \
	../debug.h ../editor.h ../gbwidget.h ../glade.h ../styles.h \
	../glade_widget_data.h ../glade-parser.h ../gbsource.h \
	../glade_project.h ../load.h ../property.h ../save.h \
	../source.h ../utils.h ../graphics/gnome-db-list.xpm
gnomedblogin.o: gnomedblogin.c ../../config.h ../gb.h ../gladeconfig.h \
	../debug.h ../editor.h ../gbwidget.h ../glade.h ../styles.h \
	../glade_widget_data.h ../glade-parser.h ../gbsource.h \
	../glade_project.h ../load.h ../property.h ../save.h \
	../source.h ../utils.h ../graphics/gnome-db-login.xpm
gnomedblogindlg.o: gnomedblogindlg.c ../../config.h ../gb.h \
	../gladeconfig.h ../debug.h ../editor.h ../gbwidget.h \
	../glade.h ../styles.h ../glade_widget_data.h ../glade-parser.h \
	../gbsource.h ../glade_project.h ../load.h ../property.h \
	../save.h ../source.h ../utils.h \
	../graphics/gnome-db-login-dlg.xpm
gnomedbprovidersel.o: gnomedbprovidersel.c ../../config.h ../gb.h \
	../gladeconfig.h ../debug.h ../editor.h ../gbwidget.h \
	../glade.h ../styles.h ../glade_widget_data.h ../glade-parser.h \
	../gbsource.h ../glade_project.h ../load.h ../property.h \
	../save.h ../source.h ../utils.h \
	../graphics/gnome-db-provider-sel.xpm
gnomedbsourcesel.o: gnomedbsourcesel.c ../../config.h ../gb.h \
	../gladeconfig.h ../debug.h ../editor.h ../gbwidget.h \
	../glade.h ../styles.h ../glade_widget_data.h ../glade-parser.h \
	../gbsource.h ../glade_project.h ../load.h ../property.h \
	../save.h ../source.h ../utils.h \
	../graphics/gnome-db-sourcesel.xpm
gnomedbsqleditor.o: gnomedbsqleditor.c ../../config.h ../gb.h \
	../gladeconfig.h ../debug.h ../editor.h ../gbwidget.h \
	../glade.h ../styles.h ../glade_widget_data.h ../glade-parser.h \
	../gbsource.h ../glade_project.h ../load.h ../property.h \
	../save.h ../source.h ../utils.h \
	../graphics/gnome-db-sql-editor.xpm
gnomedbtableeditor.o: gnomedbtableeditor.c ../../config.h ../gb.h \
	../gladeconfig.h ../debug.h ../editor.h ../gbwidget.h \
	../glade.h ../styles.h ../glade_widget_data.h ../glade-parser.h \
	../gbsource.h ../glade_project.h ../load.h ../property.h \
	../save.h ../source.h ../utils.h \
	../graphics/gnome-db-table-editor.xpm

info-am:
info: info-am
dvi-am:
dvi: dvi-am
check-am: all-am
check: check-am
installcheck-am:
installcheck: installcheck-am
install-exec-am:
install-exec: install-exec-am

install-data-am:
install-data: install-data-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am
install: install-am
uninstall-am:
uninstall: uninstall-am
all-am: Makefile $(LIBRARIES)
all-redirect: all-am
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) AM_INSTALL_PROGRAM_FLAGS=-s install
installdirs:


mostlyclean-generic:

clean-generic:

distclean-generic:
	-rm -f Makefile $(CONFIG_CLEAN_FILES)
	-rm -f config.cache config.log stamp-h stamp-h[0-9]*

maintainer-clean-generic:
mostlyclean-am:  mostlyclean-noinstLIBRARIES mostlyclean-compile \
		mostlyclean-libtool mostlyclean-tags \
		mostlyclean-generic

mostlyclean: mostlyclean-am

clean-am:  clean-noinstLIBRARIES clean-compile clean-libtool clean-tags \
		clean-generic mostlyclean-am

clean: clean-am

distclean-am:  distclean-noinstLIBRARIES distclean-compile \
		distclean-libtool distclean-tags distclean-generic \
		clean-am
	-rm -f libtool

distclean: distclean-am

maintainer-clean-am:  maintainer-clean-noinstLIBRARIES \
		maintainer-clean-compile maintainer-clean-libtool \
		maintainer-clean-tags maintainer-clean-generic \
		distclean-am
	@echo "This command is intended for maintainers to use;"
	@echo "it deletes files that may require special tools to rebuild."

maintainer-clean: maintainer-clean-am

.PHONY: mostlyclean-noinstLIBRARIES distclean-noinstLIBRARIES \
clean-noinstLIBRARIES maintainer-clean-noinstLIBRARIES \
mostlyclean-compile distclean-compile clean-compile \
maintainer-clean-compile mostlyclean-libtool distclean-libtool \
clean-libtool maintainer-clean-libtool tags mostlyclean-tags \
distclean-tags clean-tags maintainer-clean-tags distdir info-am info \
dvi-am dvi check check-am installcheck-am installcheck install-exec-am \
install-exec install-data-am install-data install-am install \
uninstall-am uninstall all-redirect all-am all installdirs \
mostlyclean-generic distclean-generic clean-generic \
maintainer-clean-generic clean mostlyclean distclean maintainer-clean


# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
